[package]
name = "hello"
version = "0.1.0"
authors = ["leochan"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"
spin = "0.4.6"
multiboot2 = "0.1.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]